// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: several.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Several {
  public static partial class SeveralService
  {
    static readonly string __ServiceName = "several.SeveralService";

    static readonly grpc::Marshaller<global::Several.SeveralRequest> __Marshaller_SeveralRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Several.SeveralRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Several.SeveralResponse> __Marshaller_SeveralResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Several.SeveralResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Several.SeveralRequest, global::Several.SeveralResponse> __Method_GetSeveralData = new grpc::Method<global::Several.SeveralRequest, global::Several.SeveralResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSeveralData",
        __Marshaller_SeveralRequest,
        __Marshaller_SeveralResponse);

    static readonly grpc::Method<global::Several.SeveralRequest, global::Several.SeveralResponse> __Method_UpdateSeveralData = new grpc::Method<global::Several.SeveralRequest, global::Several.SeveralResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateSeveralData",
        __Marshaller_SeveralRequest,
        __Marshaller_SeveralResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Several.SeveralReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SeveralService</summary>
    public abstract partial class SeveralServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Several.SeveralResponse> GetSeveralData(global::Several.SeveralRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Several.SeveralResponse> UpdateSeveralData(global::Several.SeveralRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SeveralService</summary>
    public partial class SeveralServiceClient : grpc::ClientBase<SeveralServiceClient>
    {
      /// <summary>Creates a new client for SeveralService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SeveralServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SeveralService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SeveralServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SeveralServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SeveralServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Several.SeveralResponse GetSeveralData(global::Several.SeveralRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetSeveralData(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Several.SeveralResponse GetSeveralData(global::Several.SeveralRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSeveralData, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Several.SeveralResponse> GetSeveralDataAsync(global::Several.SeveralRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetSeveralDataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Several.SeveralResponse> GetSeveralDataAsync(global::Several.SeveralRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSeveralData, null, options, request);
      }
      public virtual global::Several.SeveralResponse UpdateSeveralData(global::Several.SeveralRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateSeveralData(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Several.SeveralResponse UpdateSeveralData(global::Several.SeveralRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateSeveralData, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Several.SeveralResponse> UpdateSeveralDataAsync(global::Several.SeveralRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateSeveralDataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Several.SeveralResponse> UpdateSeveralDataAsync(global::Several.SeveralRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateSeveralData, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SeveralServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SeveralServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SeveralServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetSeveralData, serviceImpl.GetSeveralData)
          .AddMethod(__Method_UpdateSeveralData, serviceImpl.UpdateSeveralData).Build();
    }

  }
}
#endregion
